/* This file was generated by ../build-aux/gen_build_data.sh.  Do not edit manually.  */
package net.opentsdb;

/** Build data for {@code net.opentsdb} */
public final class BuildData {
  /** Version string MAJOR.MINOR.MAINT */
  public static final String version = "2.0.1";
  /** Short revision at which this package was built. */
  public static final String short_revision = "76b928d";
  /** Full revision at which this package was built. */
  public static final String full_revision = "76b928da99db7552a79e1ac04dbb3810908b8b5b";
  /** UTC date at which this package was built. */
  public static final String date = "2014/11/09 23:32:26 +0000";
  /** UNIX timestamp of the time of the build. */
  public static final long timestamp = 1415575946;

  /** Represents the status of the repository at the time of the build. */
  public static enum RepoStatus {
    /** The status of the repository was unknown at the time of the build. */
    UNKNOWN,
    /** There was no local modification during the build. */
    MINT,
    /** There were some local modifications during the build. */
    MODIFIED;
  }
  /** Status of the repository at the time of the build. */
  public static final RepoStatus repo_status = RepoStatus.MINT;

  /** Username of the user who built this package. */
  public static final String user = "root";
  /** Host on which this package was built. */
  public static final String host = "precise-gui-vm";
  /** Path to the repository in which this package was built. */
  public static final String repo = "/home/hobbes/opentsdb/build";

  /** Human readable string describing the revision of this package. */
  public static final String revisionString() {
    return "net.opentsdb 2.0.1 built at revision 76b928d (MINT)";
  }
  /** Human readable string describing the build information of this package. */
  public static final String buildString() {
    return "Built on 2014/11/09 23:32:26 +0000 by root@precise-gui-vm:/home/hobbes/opentsdb/build";
  }

  // These functions are useful to avoid cross-jar inlining.

  /** Version string MAJOR.MINOR.MAINT */
  public static String version() {
    return version;
  }
  /** Short revision at which this package was built. */
  public static String shortRevision() {
    return short_revision;
  }
  /** Full revision at which this package was built. */
  public static String fullRevision() {
    return full_revision;
  }
  /** UTC date at which this package was built. */
  public static String date() {
    return date;
  }
  /** UNIX timestamp of the time of the build. */
  public static long timestamp() {
    return timestamp;
  }
  /** Status of the repository at the time of the build. */
  public static RepoStatus repoStatus() {
    return repo_status;
  }
  /** Username of the user who built this package. */
  public static String user() {
    return user;
  }
  /** Host on which this package was built. */
  public static String host() {
    return host;
  }
  /** Path to the repository in which this package was built. */
  public static String repo() {
    return repo;
  }

  // Can't instantiate.
  private BuildData() {}
}
